### ISSUE TITLE
Relative Font URL Links

### ISSUE THREAD

**Issue by jamsinclair** [vend/peg#3]
CSS file references relative links for font files. These will need to be replaced with absolute URLs, otherwise they won't work.

Or we can include the font files in this repo.

https://github.com/vend/peg/blob/master/assets/css/app.css#L5

**Comment by ludwigw** [comment]
Hmmm absolute maybe? So third party people can rely on them. Oh wait. CORS?

**Comment by jtrotsky** [comment]
Fixed with relative paths to files https://github.com/vend/peg/tree/master/assets/fonts

**Comment by ludwigw** [comment]
Uhh, do we have a license to distribute that font to third parties?

**Comment by jtrotsky** [comment]
@ludwigw the font is Open Source as per http://www.latofonts.com/lato-free-fonts/

**Comment by jtrotsky** [comment]
Also “Lato” means “Sum­mer” in Pol­ish
